app:
  secret: Sam
server:
  port: 9095
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/springdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
